#ifndef __ERRORS_H__
#define __ERRORS_H__

enum Error {
ERR_NO_ERROR = 0,
ERR_ENGINE_INITED,
ERR_ENGINE_INVALID_MODE,
ERR_WINDOW_INVALID_WIDTH,
ERR_WINDOW_INVALID_HEIGHT,
ERR_WINDOW_INVALID_BPP,
ERR_WINDOW_INVALID_STYLE,
ERR_WINDOW_INVALID_DEPTH_BITS,
ERR_WINDOW_INVALID_STENCIL_BITS,
ERR_WINDOW_INVALID_AA_LEVEL
};

#endif//__ERRORS_H__
