#ifndef __ERRORS_H__
#define __ERRORS_H__

enum Error {
ERR_NO_ERROR = 0,
ERR_INVALID_WINDOW_WIDTH,
ERR_INVALID_WINDOW_HEIGHT,
ERR_INVALID_WINDOW_BPP,
ERR_INVALID_WINDOW_STYLE,
ERR_INVALID_WINDOW_DEPTH_BITS,
ERR_INVALID_WINDOW_STENCIL_BITS,
ERR_INVALID_WINDOW_AA_LEVEL
};

#endif//__ERRORS_H__
